[2023-10-02T00:49:56.638+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-Postgres.load_to_postgres scheduled__2019-06-02T06:00:00+00:00 [queued]>
[2023-10-02T00:49:56.655+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-Postgres.load_to_postgres scheduled__2019-06-02T06:00:00+00:00 [queued]>
[2023-10-02T00:49:56.656+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-10-02T00:49:56.717+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): load_to_postgres> on 2019-06-02 06:00:00+00:00
[2023-10-02T00:49:56.726+0000] {standard_task_runner.py:57} INFO - Started process 1124 to run task
[2023-10-02T00:49:56.729+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Load-Green-Taxi-Data-Web-To-GCS-To-Postgres', 'load_to_postgres', 'scheduled__2019-06-02T06:00:00+00:00', '--job-id', '668', '--raw', '--subdir', 'DAGS_FOLDER/web_gcs_pg.py', '--cfg-path', '/tmp/tmpsghr5l11']
[2023-10-02T00:49:56.732+0000] {standard_task_runner.py:85} INFO - Job 668: Subtask load_to_postgres
[2023-10-02T00:49:56.798+0000] {task_command.py:410} INFO - Running <TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-Postgres.load_to_postgres scheduled__2019-06-02T06:00:00+00:00 [running]> on host 537710aea1a2
[2023-10-02T00:49:56.864+0000] {abstractoperator.py:598} ERROR - Exception rendering Jinja template for task 'load_to_postgres', field 'sql'. Template: "-- create green table\nCREATE TABLE IF NOT EXISTS {{ SERVICE }} (\n       VendorID INT,\n       lpep_pickup_datetime TIMESTAMP,\n       lpep_dropoff_datetime TIMESTAMP,\n       store_and_fwd_flag STRING,\n       RatecodeID FLOAT,\n       PULocationID FLOAT,\n       DOLocationID FLOAT,\n       passenger_count FLOAT,\n       trip_distance FLOAT,\n       fare_amount FLOAT,\n       extra FLOAT,\n       mta_tax FLOAT,\n       tip_amount FLOAT,\n       tolls_amount FLOAT,\n       ehail_fee FLOAT,\n       improvement_surcharge FLOAT,\n       total_amount FLOAT,\n       payment_type FLOAT,\n       trip_type FLOAT,\n       congestion_surcharge FLOAT\n   );\n\n-- ingest data\nCOPY {{ SERVICE }} FROM '{{ PATH_TO_SAVED_FILE }}' CSV HEADER;\n"
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 156, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 540, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 113, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 14, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'SERVICE' is undefined
[2023-10-02T00:49:56.865+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 156, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 540, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 113, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 14, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'SERVICE' is undefined
[2023-10-02T00:49:56.875+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=Load-Green-Taxi-Data-Web-To-GCS-To-Postgres, task_id=load_to_postgres, execution_date=20190602T060000, start_date=20231002T004956, end_date=20231002T004956
[2023-10-02T00:49:56.894+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 668 for task load_to_postgres ('SERVICE' is undefined; 1124)
[2023-10-02T00:49:56.941+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-10-02T00:49:56.969+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
