[2023-10-02T02:44:13.584+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-Postgres.load_to_postgres scheduled__2020-04-02T06:00:00+00:00 [queued]>
[2023-10-02T02:44:13.595+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-Postgres.load_to_postgres scheduled__2020-04-02T06:00:00+00:00 [queued]>
[2023-10-02T02:44:13.595+0000] {taskinstance.py:1308} INFO - Starting attempt 3 of 3
[2023-10-02T02:44:13.622+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2020-04-02 06:00:00+00:00
[2023-10-02T02:44:13.630+0000] {standard_task_runner.py:57} INFO - Started process 3216 to run task
[2023-10-02T02:44:13.633+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Load-Green-Taxi-Data-Web-To-GCS-To-Postgres', 'load_to_postgres', 'scheduled__2020-04-02T06:00:00+00:00', '--job-id', '717', '--raw', '--subdir', 'DAGS_FOLDER/web_gcs_pg.py', '--cfg-path', '/tmp/tmptmpqeqcu']
[2023-10-02T02:44:13.635+0000] {standard_task_runner.py:85} INFO - Job 717: Subtask load_to_postgres
[2023-10-02T02:44:13.770+0000] {task_command.py:410} INFO - Running <TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-Postgres.load_to_postgres scheduled__2020-04-02T06:00:00+00:00 [running]> on host 537710aea1a2
[2023-10-02T02:44:13.945+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Load-Green-Taxi-Data-Web-To-GCS-To-Postgres' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2020-04-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-04-02T06:00:00+00:00'
[2023-10-02T02:44:13.955+0000] {base.py:73} INFO - Using connection ID 'my_postgres_conn' for task execution.
[2023-10-02T02:44:13.959+0000] {sql.py:375} INFO - Running statement: 
		    -- create green table
		    CREATE TABLE IF NOT EXISTS green_taxi (
		        VendorID INT,
		        lpep_pickup_datetime TIMESTAMP,
		        lpep_dropoff_datetime TIMESTAMP,
		        store_and_fwd_flag VARCHAR,
		        RatecodeID FLOAT,
		        PULocationID FLOAT,
		        DOLocationID FLOAT,
		        passenger_count FLOAT,
		        trip_distance FLOAT,
		        fare_amount FLOAT,
		        extra FLOAT,
		        mta_tax FLOAT,
		        tip_amount FLOAT,
		        tolls_amount FLOAT,
		        ehail_fee FLOAT,
		        improvement_surcharge FLOAT,
		        total_amount FLOAT,
		        payment_type FLOAT,
		        trip_type FLOAT,
		        congestion_surcharge FLOAT
		    );

		    -- ingest data
		    COPY green_taxi FROM 'green_tripdata_{{ dag_run.logical_date.strftime('%Y-%m') }}.csv' DELIMITER ',' CSV HEADER;
		, parameters: None
[2023-10-02T02:44:13.960+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/web_gcs_pg.py", line 92, in load_data_to_postgres
    postgres_hook.run(sql)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "%"
LINE 27: ...'green_tripdata_{{ dag_run.logical_date.strftime('%Y-%m') }}...
                                                              ^

[2023-10-02T02:44:14.024+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=Load-Green-Taxi-Data-Web-To-GCS-To-Postgres, task_id=load_to_postgres, execution_date=20200402T060000, start_date=20231002T024413, end_date=20231002T024414
[2023-10-02T02:44:14.047+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:153: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2023-10-02T02:44:14.047+0000] {configuration.py:673} WARNING - section/key [smtp/smtp_user] not found in config
[2023-10-02T02:44:14.048+0000] {email.py:269} INFO - Email alerting: attempt 1
[2023-10-02T02:44:14.059+0000] {configuration.py:673} WARNING - section/key [smtp/smtp_user] not found in config
[2023-10-02T02:44:14.060+0000] {email.py:269} INFO - Email alerting: attempt 1
[2023-10-02T02:44:14.060+0000] {taskinstance.py:1889} ERROR - Failed to send email to: ['']
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1558, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1628, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/web_gcs_pg.py", line 92, in load_data_to_postgres
    postgres_hook.run(sql)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.SyntaxError: syntax error at or near "%"
LINE 27: ...'green_tripdata_{{ dag_run.logical_date.strftime('%Y-%m') }}...
                                                              ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2295, in email_alert
    send_email(task.email, subject, html_content)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 92, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 153, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 271, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 318, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1887, in handle_failure
    self.email_alert(error, task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2297, in email_alert
    send_email(task.email, subject, html_content_err)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 92, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 153, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 271, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 318, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2023-10-02T02:44:14.166+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 717 for task load_to_postgres (syntax error at or near "%"
LINE 27: ...'green_tripdata_{{ dag_run.logical_date.strftime('%Y-%m') }}...
                                                              ^
; 3216)
[2023-10-02T02:44:14.208+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-10-02T02:44:14.246+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
